puts "  ABCDEFGHIJKLMNOPQRSTUVWXYZ"
puts "  __________________________ "
puts "1|                          |"
puts "2|                          |"
puts "3|                          |"
puts "4|                          |"
puts "5|                          |"
puts "6|                          |"
puts "7|                          |"
puts "8|                          |"
puts "9|                          |"
puts "  --------------------------"
  print "Question 1: Type 4? "
  x = gets.strip.capitalize
    if x == 4.to_s
      puts "  ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      puts "  __________________________ "
      puts "1|XXXX                      |"
      puts "2|                          |"
      puts "3|                          |"
      puts "4|                          |"
      puts "5|                          |"
      puts "6|                          |"
      puts "7|                          |"
      puts "8|                          |"
      puts "9|                          |"
      puts "  -------------------------- "
    else
      puts "Try again"
    end
